export interface CidadeOption {
  cidade: string;
  estado: string;
}

export const CIDADES: CidadeOption[] = [
  // Norte
  { cidade: "Manaus", estado: "AM" },
  { cidade: "Belém", estado: "PA" },
  { cidade: "Santarém", estado: "PA" },
  { cidade: "Ananindeua", estado: "PA" },
  { cidade: "Porto Velho", estado: "RO" },
  { cidade: "Rio Branco", estado: "AC" },
  { cidade: "Boa Vista", estado: "RR" },
  { cidade: "Macapá", estado: "AP" },
  { cidade: "Palmas", estado: "TO" },
  // Nordeste
  { cidade: "Salvador", estado: "BA" },
  { cidade: "Feira de Santana", estado: "BA" },
  { cidade: "Camaçari", estado: "BA" },
  { cidade: "Fortaleza", estado: "CE" },
  { cidade: "Caucaia", estado: "CE" },
  { cidade: "Juazeiro do Norte", estado: "CE" },
  { cidade: "Recife", estado: "PE" },
  { cidade: "Jaboatão dos Guararapes", estado: "PE" },
  { cidade: "Olinda", estado: "PE" },
  { cidade: "Caruaru", estado: "PE" },
  { cidade: "Natal", estado: "RN" },
  { cidade: "Mossoró", estado: "RN" },
  { cidade: "João Pessoa", estado: "PB" },
  { cidade: "Campina Grande", estado: "PB" },
  { cidade: "Maceió", estado: "AL" },
  { cidade: "Aracaju", estado: "SE" },
  { cidade: "São Luís", estado: "MA" },
  { cidade: "Imperatriz", estado: "MA" },
  { cidade: "Teresina", estado: "PI" },
  // Centro-Oeste
  { cidade: "Brasília", estado: "DF" },
  { cidade: "Goiânia", estado: "GO" },
  { cidade: "Aparecida de Goiânia", estado: "GO" },
  { cidade: "Anápolis", estado: "GO" },
  { cidade: "Campo Grande", estado: "MS" },
  { cidade: "Dourados", estado: "MS" },
  { cidade: "Cuiabá", estado: "MT" },
  // Sudeste
  { cidade: "São Paulo", estado: "SP" },
  { cidade: "Guarulhos", estado: "SP" },
  { cidade: "Campinas", estado: "SP" },
  { cidade: "São Bernardo do Campo", estado: "SP" },
  { cidade: "Santo André", estado: "SP" },
  { cidade: "Osasco", estado: "SP" },
  { cidade: "Ribeirão Preto", estado: "SP" },
  { cidade: "Sorocaba", estado: "SP" },
  { cidade: "Mogi das Cruzes", estado: "SP" },
  { cidade: "São José dos Campos", estado: "SP" },
  { cidade: "Santos", estado: "SP" },
  { cidade: "Rio de Janeiro", estado: "RJ" },
  { cidade: "Niterói", estado: "RJ" },
  { cidade: "São Gonçalo", estado: "RJ" },
  { cidade: "Duque de Caxias", estado: "RJ" },
  { cidade: "Nova Iguaçu", estado: "RJ" },
  { cidade: "Belo Horizonte", estado: "MG" },
  { cidade: "Contagem", estado: "MG" },
  { cidade: "Uberlândia", estado: "MG" },
  { cidade: "Juiz de Fora", estado: "MG" },
  { cidade: "Betim", estado: "MG" },
  { cidade: "Montes Claros", estado: "MG" },
  { cidade: "Vitória", estado: "ES" },
  { cidade: "Serra", estado: "ES" },
  { cidade: "Vila Velha", estado: "ES" },
  // Sul
  { cidade: "Curitiba", estado: "PR" },
  { cidade: "Londrina", estado: "PR" },
  { cidade: "Maringá", estado: "PR" },
  { cidade: "Cascavel", estado: "PR" },
  { cidade: "Florianópolis", estado: "SC" },
  { cidade: "Joinville", estado: "SC" },
  { cidade: "Blumenau", estado: "SC" },
  { cidade: "Chapecó", estado: "SC" },
  { cidade: "Porto Alegre", estado: "RS" },
  { cidade: "Caxias do Sul", estado: "RS" },
  { cidade: "Pelotas", estado: "RS" },
  { cidade: "Canoas", estado: "RS" },
  { cidade: "Santa Maria", estado: "RS" },
];
